parameters:
    connection: somesqlinstance
    user: 123
    carname: CoolCar

services:
    car_service:
        class: \TestServices\Car
        arguments: [222, '@engine_service', \TestServices\CarSoundType, CoolLogo, '%carname']

    truck_service:
        class: \TestServices\Truck
        arguments: '%connection'

    super_truck_service:
        class: \TestServices\Truck
        arguments: '@car_service'

    engine_service:
        class: \TestServices\CarEngine