parameters:
    connection: somesqlinstance
    user: 123

services:
    car_service:
        class: \TestServices\Car
        arguments: [123, '@truck_service', \TestServices\Truck, string, '%connection']

    truck_service:
        class: \TestServices\Truck
        arguments: '%connection'

    super_truck_service:
        class: \TestServices\Truck
        arguments: '@car_service'